///************************************************
/// Generated by: Hungtd
/// Date: 19/08/2011 11:34:03
/// Goal: Create User Service Class for DM_CUSTOMER
///************************************************
/// <summary>
/// Create User Service Class for DM_CUSTOMER
/// </summary>


using SaleDS;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;


namespace SaleUS
{
    public class US_DM_CUSTOMER : US_Object
    {
        private const string c_TableName = "DM_CUSTOMER";
        #region Public Properties
        public decimal dcID
        {
            get
            {
                return CNull.RowNVLDecimal(pm_objDR, "ID", IPConstants.c_DefaultDecimal);
            }
            set
            {
                pm_objDR["ID"] = value;
            }
        }

        public bool IsIDNull()
        {
            return pm_objDR.IsNull("ID");
        }

        public void SetIDNull()
        {
            pm_objDR["ID"] = System.Convert.DBNull;
        }

        public decimal dcCUSTOMER_GROUP_ID
        {
            get
            {
                return CNull.RowNVLDecimal(pm_objDR, "CUSTOMER_GROUP_ID", IPConstants.c_DefaultDecimal);
            }
            set
            {
                pm_objDR["CUSTOMER_GROUP_ID"] = value;
            }
        }

        public bool IsCUSTOMER_GROUP_IDNull()
        {
            return pm_objDR.IsNull("CUSTOMER_GROUP_ID");
        }

        public void SetCUSTOMER_GROUP_IDNull()
        {
            pm_objDR["CUSTOMER_GROUP_ID"] = System.Convert.DBNull;
        }

        public string strCUSTOMER_NAME
        {
            get
            {
                return CNull.RowNVLString(pm_objDR, "CUSTOMER_NAME", IPConstants.c_DefaultString);
            }
            set
            {
                pm_objDR["CUSTOMER_NAME"] = value;
            }
        }

        public bool IsCUSTOMER_NAMENull()
        {
            return pm_objDR.IsNull("CUSTOMER_NAME");
        }

        public void SetCUSTOMER_NAMENull()
        {
            pm_objDR["CUSTOMER_NAME"] = System.Convert.DBNull;
        }

        public string strMOBLIE_PHONE
        {
            get
            {
                return CNull.RowNVLString(pm_objDR, "MOBLIE_PHONE", IPConstants.c_DefaultString);
            }
            set
            {
                pm_objDR["MOBLIE_PHONE"] = value;
            }
        }

        public bool IsMOBLIE_PHONENull()
        {
            return pm_objDR.IsNull("MOBLIE_PHONE");
        }

        public void SetMOBLIE_PHONENull()
        {
            pm_objDR["MOBLIE_PHONE"] = System.Convert.DBNull;
        }

        public string strEMAIL
        {
            get
            {
                return CNull.RowNVLString(pm_objDR, "EMAIL", IPConstants.c_DefaultString);
            }
            set
            {
                pm_objDR["EMAIL"] = value;
            }
        }

        public bool IsEMAILNull()
        {
            return pm_objDR.IsNull("EMAIL");
        }

        public void SetEMAILNull()
        {
            pm_objDR["EMAIL"] = System.Convert.DBNull;
        }

        public string strADDRESS
        {
            get
            {
                return CNull.RowNVLString(pm_objDR, "ADDRESS", IPConstants.c_DefaultString);
            }
            set
            {
                pm_objDR["ADDRESS"] = value;
            }
        }

        public bool IsADDRESSNull()
        {
            return pm_objDR.IsNull("ADDRESS");
        }

        public void SetADDRESSNull()
        {
            pm_objDR["ADDRESS"] = System.Convert.DBNull;
        }

        public string strWEBSITE
        {
            get
            {
                return CNull.RowNVLString(pm_objDR, "WEBSITE", IPConstants.c_DefaultString);
            }
            set
            {
                pm_objDR["WEBSITE"] = value;
            }
        }

        public bool IsWEBSITENull()
        {
            return pm_objDR.IsNull("WEBSITE");
        }

        public void SetWEBSITENull()
        {
            pm_objDR["WEBSITE"] = System.Convert.DBNull;
        }

        public string strTAX_CODE
        {
            get
            {
                return CNull.RowNVLString(pm_objDR, "TAX_CODE", IPConstants.c_DefaultString);
            }
            set
            {
                pm_objDR["TAX_CODE"] = value;
            }
        }

        public bool IsTAX_CODENull()
        {
            return pm_objDR.IsNull("TAX_CODE");
        }

        public void SetTAX_CODENull()
        {
            pm_objDR["TAX_CODE"] = System.Convert.DBNull;
        }

        #endregion


        #region Init Functions
        public US_DM_CUSTOMER()
        {
            pm_objDS = new DS_DM_CUSTOMER();
            pm_strTableName = c_TableName;
            pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
        }

        public US_DM_CUSTOMER(DataRow i_objDR)
            : this()
        {
            this.DataRow2Me(i_objDR);
        }

        public US_DM_CUSTOMER(decimal i_dbID)
        {
            pm_objDS = new DS_DM_CUSTOMER();
            pm_strTableName = c_TableName;
            IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
            v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
            SqlCommand v_cmdSQL;
            v_cmdSQL = v_objMkCmd.getSelectCmd();
            this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
            pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
        }
        #endregion


     

    }
}
