///************************************************
/// Generated by: uyvq
/// Date: 19/08/2011 02:48:08
/// Goal: Create User Service Class for DM_PROVIDER
///************************************************
/// <summary>
/// Create User Service Class for DM_PROVIDER
/// </summary>


using SaleDS;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;


namespace SaleUS
{
public class US_DM_PROVIDER : US_Object
{
	private const string c_TableName = "DM_PROVIDER";
#region Public Properties
	public decimal dcID 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID"] = value;
		}
	}

	public bool IsIDNull()	{
		return pm_objDR.IsNull("ID");
	}

	public void SetIDNull() {
		pm_objDR["ID"] = System.Convert.DBNull;
	}

	public string strPROVIDER_CODE 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "PROVIDER_CODE", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["PROVIDER_CODE"] = value;
		}
	}

	public bool IsPROVIDER_CODENull() 
	{
		return pm_objDR.IsNull("PROVIDER_CODE");
	}

	public void SetPROVIDER_CODENull() {
		pm_objDR["PROVIDER_CODE"] = System.Convert.DBNull;
	}

	public string strPROVIDER_NAME 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "PROVIDER_NAME", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["PROVIDER_NAME"] = value;
		}
	}

	public bool IsPROVIDER_NAMENull() 
	{
		return pm_objDR.IsNull("PROVIDER_NAME");
	}

	public void SetPROVIDER_NAMENull() {
		pm_objDR["PROVIDER_NAME"] = System.Convert.DBNull;
	}

	public string strMOBILE 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "MOBILE", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["MOBILE"] = value;
		}
	}

	public bool IsMOBILENull() 
	{
		return pm_objDR.IsNull("MOBILE");
	}

	public void SetMOBILENull() {
		pm_objDR["MOBILE"] = System.Convert.DBNull;
	}

	public string strEMAIL 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "EMAIL", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["EMAIL"] = value;
		}
	}

	public bool IsEMAILNull() 
	{
		return pm_objDR.IsNull("EMAIL");
	}

	public void SetEMAILNull() {
		pm_objDR["EMAIL"] = System.Convert.DBNull;
	}

	public string strADDRESS 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "ADDRESS", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["ADDRESS"] = value;
		}
	}

	public bool IsADDRESSNull() 
	{
		return pm_objDR.IsNull("ADDRESS");
	}

	public void SetADDRESSNull() {
		pm_objDR["ADDRESS"] = System.Convert.DBNull;
	}

	public string strTAX_CODE 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "TAX_CODE", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["TAX_CODE"] = value;
		}
	}

	public bool IsTAX_CODENull() 
	{
		return pm_objDR.IsNull("TAX_CODE");
	}

	public void SetTAX_CODENull() {
		pm_objDR["TAX_CODE"] = System.Convert.DBNull;
	}

#endregion


#region Init Functions
	public US_DM_PROVIDER() 
	{
		pm_objDS = new DS_DM_PROVIDER();
		pm_strTableName = c_TableName;
		pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
	}

	public US_DM_PROVIDER(DataRow i_objDR): this()
	{
		this.DataRow2Me(i_objDR);
	}

	public US_DM_PROVIDER(decimal i_dbID) 
	{
		pm_objDS = new DS_DM_PROVIDER();
		pm_strTableName = c_TableName;
		IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
		v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
		SqlCommand v_cmdSQL;
		v_cmdSQL = v_objMkCmd.getSelectCmd();
		this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
		pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
	}
#endregion


  }
}
