///************************************************
/// Generated by: MinhNN
/// Date: 19/08/2011 11:38:40
/// Goal: Create User Service Class for DM_COMPANY_INFO
///************************************************
/// <summary>
/// Create User Service Class for DM_COMPANY_INFO
/// </summary>


using SaleDS;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;


namespace SaleUS
{
public class US_DM_COMPANY_INFO : US_Object
{
	private const string c_TableName = "DM_COMPANY_INFO";
#region Public Properties
	public decimal dcID 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID"] = value;
		}
	}

	public bool IsIDNull()	{
		return pm_objDR.IsNull("ID");
	}

	public void SetIDNull() {
		pm_objDR["ID"] = System.Convert.DBNull;
	}

	public string strSHORT_NAME 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "SHORT_NAME", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["SHORT_NAME"] = value;
		}
	}

	public bool IsSHORT_NAMENull() 
	{
		return pm_objDR.IsNull("SHORT_NAME");
	}

	public void SetSHORT_NAMENull() {
		pm_objDR["SHORT_NAME"] = System.Convert.DBNull;
	}

	public string strFULL_NAME 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "FULL_NAME", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["FULL_NAME"] = value;
		}
	}

	public bool IsFULL_NAMENull() 
	{
		return pm_objDR.IsNull("FULL_NAME");
	}

	public void SetFULL_NAMENull() {
		pm_objDR["FULL_NAME"] = System.Convert.DBNull;
	}

	public string strADDRESS 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "ADDRESS", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["ADDRESS"] = value;
		}
	}

	public bool IsADDRESSNull() 
	{
		return pm_objDR.IsNull("ADDRESS");
	}

	public void SetADDRESSNull() {
		pm_objDR["ADDRESS"] = System.Convert.DBNull;
	}

	public string strMOBLIE 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "MOBLIE", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["MOBLIE"] = value;
		}
	}

	public bool IsMOBLIENull() 
	{
		return pm_objDR.IsNull("MOBLIE");
	}

	public void SetMOBLIENull() {
		pm_objDR["MOBLIE"] = System.Convert.DBNull;
	}

	public string strEMAIL 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "EMAIL", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["EMAIL"] = value;
		}
	}

	public bool IsEMAILNull() 
	{
		return pm_objDR.IsNull("EMAIL");
	}

	public void SetEMAILNull() {
		pm_objDR["EMAIL"] = System.Convert.DBNull;
	}

	public string strTAX_CODE 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "TAX_CODE", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["TAX_CODE"] = value;
		}
	}

	public bool IsTAX_CODENull() 
	{
		return pm_objDR.IsNull("TAX_CODE");
	}

	public void SetTAX_CODENull() {
		pm_objDR["TAX_CODE"] = System.Convert.DBNull;
	}

#endregion


#region Init Functions
	public US_DM_COMPANY_INFO() 
	{
		pm_objDS = new DS_DM_COMPANY_INFO();
		pm_strTableName = c_TableName;
		pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
	}

	public US_DM_COMPANY_INFO(DataRow i_objDR): this()
	{
		this.DataRow2Me(i_objDR);
	}

	public US_DM_COMPANY_INFO(decimal i_dbID) 
	{
		pm_objDS = new DS_DM_COMPANY_INFO();
		pm_strTableName = c_TableName;
		IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
		v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
		SqlCommand v_cmdSQL;
		v_cmdSQL = v_objMkCmd.getSelectCmd();
		this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
		pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
	}
#endregion


  }
}
