///************************************************
/// Generated by: linhdh
/// Date: 30/08/2011 02:33:46
/// Goal: Create User Service Class for GD_DELIVERY_ORDER_DETAIL
///************************************************
/// <summary>
/// Create User Service Class for GD_DELIVERY_ORDER_DETAIL
/// </summary>

using System;
using SaleDS;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;


namespace SaleUS
{
public class US_GD_DELIVERY_ORDER_DETAIL : US_Object
{
	private const string c_TableName = "GD_DELIVERY_ORDER_DETAIL";
#region Public Properties
	public decimal dcID 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID"] = value;
		}
	}

	public bool IsIDNull()	{
		return pm_objDR.IsNull("ID");
	}

	public void SetIDNull() {
		pm_objDR["ID"] = System.Convert.DBNull;
	}

	public decimal dcDELIVERY_ORDER_ID 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "DELIVERY_ORDER_ID", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["DELIVERY_ORDER_ID"] = value;
		}
	}

	public bool IsDELIVERY_ORDER_IDNull()	{
		return pm_objDR.IsNull("DELIVERY_ORDER_ID");
	}

	public void SetDELIVERY_ORDER_IDNull() {
		pm_objDR["DELIVERY_ORDER_ID"] = System.Convert.DBNull;
	}

	public decimal dcPRODUCT_ID 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "PRODUCT_ID", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["PRODUCT_ID"] = value;
		}
	}

	public bool IsPRODUCT_IDNull()	{
		return pm_objDR.IsNull("PRODUCT_ID");
	}

	public void SetPRODUCT_IDNull() {
		pm_objDR["PRODUCT_ID"] = System.Convert.DBNull;
	}

	public decimal dcQUANTITY 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "QUANTITY", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["QUANTITY"] = value;
		}
	}

	public bool IsQUANTITYNull()	{
		return pm_objDR.IsNull("QUANTITY");
	}

	public void SetQUANTITYNull() {
		pm_objDR["QUANTITY"] = System.Convert.DBNull;
	}

#endregion


#region Init Functions
	public US_GD_DELIVERY_ORDER_DETAIL() 
	{
		pm_objDS = new DS_GD_DELIVERY_ORDER_DETAIL();
		pm_strTableName = c_TableName;
		pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
	}

	public US_GD_DELIVERY_ORDER_DETAIL(DataRow i_objDR): this()
	{
		this.DataRow2Me(i_objDR);
	}

	public US_GD_DELIVERY_ORDER_DETAIL(decimal i_dbID) 
	{
		pm_objDS = new DS_GD_DELIVERY_ORDER_DETAIL();
		pm_strTableName = c_TableName;
		IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
		v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
		SqlCommand v_cmdSQL;
		v_cmdSQL = v_objMkCmd.getSelectCmd();
		this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
		pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
	}
#endregion


  }
}
