'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System


<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0"),  _
 Serializable(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.ComponentModel.ToolboxItem(true),  _
 System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema"),  _
 System.Xml.Serialization.XmlRootAttribute("DS_HT_NGUOI_SU_DUNG"),  _
 System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")>  _
Partial Public Class DS_HT_NGUOI_SU_DUNG
    Inherits System.Data.DataSet
    
    Private tableHT_NGUOI_SU_DUNG As HT_NGUOI_SU_DUNGDataTable
    
    Private _schemaSerializationMode As System.Data.SchemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Sub New()
        MyBase.New
        Me.BeginInit
        Me.InitClass
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
        AddHandler MyBase.Relations.CollectionChanged, schemaChangedHandler
        Me.EndInit
    End Sub
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Sub New(ByVal info As System.Runtime.Serialization.SerializationInfo, ByVal context As System.Runtime.Serialization.StreamingContext)
        MyBase.New(info, context, false)
        If (Me.IsBinarySerialized(info, context) = true) Then
            Me.InitVars(false)
            Dim schemaChangedHandler1 As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
            AddHandler Me.Tables.CollectionChanged, schemaChangedHandler1
            AddHandler Me.Relations.CollectionChanged, schemaChangedHandler1
            Return
        End If
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(String)),String)
        If (Me.DetermineSchemaSerializationMode(info, context) = System.Data.SchemaSerializationMode.IncludeSchema) Then
            Dim ds As System.Data.DataSet = New System.Data.DataSet
            ds.ReadXmlSchema(New System.Xml.XmlTextReader(New System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("HT_NGUOI_SU_DUNG")) Is Nothing) Then
                MyBase.Tables.Add(New HT_NGUOI_SU_DUNGDataTable(ds.Tables("HT_NGUOI_SU_DUNG")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.ReadXmlSchema(New System.Xml.XmlTextReader(New System.IO.StringReader(strSchema)))
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     System.ComponentModel.Browsable(false),  _
     System.ComponentModel.DesignerSerializationVisibility(System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property HT_NGUOI_SU_DUNG() As HT_NGUOI_SU_DUNGDataTable
        Get
            Return Me.tableHT_NGUOI_SU_DUNG
        End Get
    End Property
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     System.ComponentModel.BrowsableAttribute(true),  _
     System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Visible)>  _
    Public Overrides Property SchemaSerializationMode() As System.Data.SchemaSerializationMode
        Get
            Return Me._schemaSerializationMode
        End Get
        Set
            Me._schemaSerializationMode = value
        End Set
    End Property
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Shadows ReadOnly Property Tables() As System.Data.DataTableCollection
        Get
            Return MyBase.Tables
        End Get
    End Property
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Shadows ReadOnly Property Relations() As System.Data.DataRelationCollection
        Get
            Return MyBase.Relations
        End Get
    End Property
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Sub InitializeDerivedDataSet()
        Me.BeginInit
        Me.InitClass
        Me.EndInit
    End Sub
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Overrides Function Clone() As System.Data.DataSet
        Dim cln As DS_HT_NGUOI_SU_DUNG = CType(MyBase.Clone,DS_HT_NGUOI_SU_DUNG)
        cln.InitVars
        cln.SchemaSerializationMode = Me.SchemaSerializationMode
        Return cln
    End Function
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As System.Xml.XmlReader)
        If (Me.DetermineSchemaSerializationMode(reader) = System.Data.SchemaSerializationMode.IncludeSchema) Then
            Me.Reset
            Dim ds As System.Data.DataSet = New System.Data.DataSet
            ds.ReadXml(reader)
            If (Not (ds.Tables("HT_NGUOI_SU_DUNG")) Is Nothing) Then
                MyBase.Tables.Add(New HT_NGUOI_SU_DUNGDataTable(ds.Tables("HT_NGUOI_SU_DUNG")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.ReadXml(reader)
            Me.InitVars
        End If
    End Sub
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Function GetSchemaSerializable() As System.Xml.Schema.XmlSchema
        Dim stream As System.IO.MemoryStream = New System.IO.MemoryStream
        Me.WriteXmlSchema(New System.Xml.XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return System.Xml.Schema.XmlSchema.Read(New System.Xml.XmlTextReader(stream), Nothing)
    End Function
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Friend Overloads Sub InitVars()
        Me.InitVars(true)
    End Sub
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Friend Overloads Sub InitVars(ByVal initTable As Boolean)
        Me.tableHT_NGUOI_SU_DUNG = CType(MyBase.Tables("HT_NGUOI_SU_DUNG"),HT_NGUOI_SU_DUNGDataTable)
        If (initTable = true) Then
            If (Not (Me.tableHT_NGUOI_SU_DUNG) Is Nothing) Then
                Me.tableHT_NGUOI_SU_DUNG.InitVars
            End If
        End If
    End Sub
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Private Sub InitClass()
        Me.DataSetName = "DS_HT_NGUOI_SU_DUNG"
        Me.Prefix = ""
        Me.Namespace = "http://tempuri.org/DS_HT_NGUOI_SU_DUNG.xsd"
        Me.EnforceConstraints = true
        Me.SchemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema
        Me.tableHT_NGUOI_SU_DUNG = New HT_NGUOI_SU_DUNGDataTable
        MyBase.Tables.Add(Me.tableHT_NGUOI_SU_DUNG)
    End Sub
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Private Function ShouldSerializeHT_NGUOI_SU_DUNG() As Boolean
        Return false
    End Function
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Shared Function GetTypedDataSetSchema(ByVal xs As System.Xml.Schema.XmlSchemaSet) As System.Xml.Schema.XmlSchemaComplexType
        Dim ds As DS_HT_NGUOI_SU_DUNG = New DS_HT_NGUOI_SU_DUNG
        Dim type As System.Xml.Schema.XmlSchemaComplexType = New System.Xml.Schema.XmlSchemaComplexType
        Dim sequence As System.Xml.Schema.XmlSchemaSequence = New System.Xml.Schema.XmlSchemaSequence
        xs.Add(ds.GetSchemaSerializable)
        Dim any As System.Xml.Schema.XmlSchemaAny = New System.Xml.Schema.XmlSchemaAny
        any.Namespace = ds.Namespace
        sequence.Items.Add(any)
        type.Particle = sequence
        Return type
    End Function
    
    Public Delegate Sub HT_NGUOI_SU_DUNGRowChangeEventHandler(ByVal sender As Object, ByVal e As HT_NGUOI_SU_DUNGRowChangeEvent)
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0"),  _
     System.Serializable(),  _
     System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")>  _
    Partial Public Class HT_NGUOI_SU_DUNGDataTable
        Inherits System.Data.DataTable
        Implements System.Collections.IEnumerable
        
        Private columnID As System.Data.DataColumn
        
        Private columnTEN_TRUY_CAP As System.Data.DataColumn
        
        Private columnTEN As System.Data.DataColumn
        
        Private columnMAT_KHAU As System.Data.DataColumn
        
        Private columnNGAY_TAO As System.Data.DataColumn
        
        Private columnNGUOI_TAO As System.Data.DataColumn
        
        Private columnTRANG_THAI As System.Data.DataColumn
        
        Private columnBUILT_IN_YN As System.Data.DataColumn
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub New()
            MyBase.New
            Me.TableName = "HT_NGUOI_SU_DUNG"
            Me.BeginInit
            Me.InitClass
            Me.EndInit
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Friend Sub New(ByVal table As System.Data.DataTable)
            MyBase.New
            Me.TableName = table.TableName
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Sub New(ByVal info As System.Runtime.Serialization.SerializationInfo, ByVal context As System.Runtime.Serialization.StreamingContext)
            MyBase.New(info, context)
            Me.InitVars
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property IDColumn() As System.Data.DataColumn
            Get
                Return Me.columnID
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property TEN_TRUY_CAPColumn() As System.Data.DataColumn
            Get
                Return Me.columnTEN_TRUY_CAP
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property TENColumn() As System.Data.DataColumn
            Get
                Return Me.columnTEN
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property MAT_KHAUColumn() As System.Data.DataColumn
            Get
                Return Me.columnMAT_KHAU
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property NGAY_TAOColumn() As System.Data.DataColumn
            Get
                Return Me.columnNGAY_TAO
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property NGUOI_TAOColumn() As System.Data.DataColumn
            Get
                Return Me.columnNGUOI_TAO
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property TRANG_THAIColumn() As System.Data.DataColumn
            Get
                Return Me.columnTRANG_THAI
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property BUILT_IN_YNColumn() As System.Data.DataColumn
            Get
                Return Me.columnBUILT_IN_YN
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count() As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Default ReadOnly Property Item(ByVal index As Integer) As HT_NGUOI_SU_DUNGRow
            Get
                Return CType(Me.Rows(index),HT_NGUOI_SU_DUNGRow)
            End Get
        End Property
        
        Public Event HT_NGUOI_SU_DUNGRowChanging As HT_NGUOI_SU_DUNGRowChangeEventHandler
        
        Public Event HT_NGUOI_SU_DUNGRowChanged As HT_NGUOI_SU_DUNGRowChangeEventHandler
        
        Public Event HT_NGUOI_SU_DUNGRowDeleting As HT_NGUOI_SU_DUNGRowChangeEventHandler
        
        Public Event HT_NGUOI_SU_DUNGRowDeleted As HT_NGUOI_SU_DUNGRowChangeEventHandler
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overloads Sub AddHT_NGUOI_SU_DUNGRow(ByVal row As HT_NGUOI_SU_DUNGRow)
            Me.Rows.Add(row)
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overloads Function AddHT_NGUOI_SU_DUNGRow(ByVal ID As Decimal, ByVal TEN_TRUY_CAP As String, ByVal TEN As String, ByVal MAT_KHAU As String, ByVal NGAY_TAO As Date, ByVal NGUOI_TAO As String, ByVal TRANG_THAI As String, ByVal BUILT_IN_YN As String) As HT_NGUOI_SU_DUNGRow
            Dim rowHT_NGUOI_SU_DUNGRow As HT_NGUOI_SU_DUNGRow = CType(Me.NewRow,HT_NGUOI_SU_DUNGRow)
            rowHT_NGUOI_SU_DUNGRow.ItemArray = New Object() {ID, TEN_TRUY_CAP, TEN, MAT_KHAU, NGAY_TAO, NGUOI_TAO, TRANG_THAI, BUILT_IN_YN}
            Me.Rows.Add(rowHT_NGUOI_SU_DUNGRow)
            Return rowHT_NGUOI_SU_DUNGRow
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function FindByID(ByVal ID As Decimal) As HT_NGUOI_SU_DUNGRow
            Return CType(Me.Rows.Find(New Object() {ID}),HT_NGUOI_SU_DUNGRow)
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overridable Function GetEnumerator() As System.Collections.IEnumerator Implements System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overrides Function Clone() As System.Data.DataTable
            Dim cln As HT_NGUOI_SU_DUNGDataTable = CType(MyBase.Clone,HT_NGUOI_SU_DUNGDataTable)
            cln.InitVars
            Return cln
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Function CreateInstance() As System.Data.DataTable
            Return New HT_NGUOI_SU_DUNGDataTable
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Friend Sub InitVars()
            Me.columnID = MyBase.Columns("ID")
            Me.columnTEN_TRUY_CAP = MyBase.Columns("TEN_TRUY_CAP")
            Me.columnTEN = MyBase.Columns("TEN")
            Me.columnMAT_KHAU = MyBase.Columns("MAT_KHAU")
            Me.columnNGAY_TAO = MyBase.Columns("NGAY_TAO")
            Me.columnNGUOI_TAO = MyBase.Columns("NGUOI_TAO")
            Me.columnTRANG_THAI = MyBase.Columns("TRANG_THAI")
            Me.columnBUILT_IN_YN = MyBase.Columns("BUILT_IN_YN")
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Private Sub InitClass()
            Me.columnID = New System.Data.DataColumn("ID", GetType(Decimal), Nothing, System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnID)
            Me.columnTEN_TRUY_CAP = New System.Data.DataColumn("TEN_TRUY_CAP", GetType(String), Nothing, System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnTEN_TRUY_CAP)
            Me.columnTEN = New System.Data.DataColumn("TEN", GetType(String), Nothing, System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnTEN)
            Me.columnMAT_KHAU = New System.Data.DataColumn("MAT_KHAU", GetType(String), Nothing, System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnMAT_KHAU)
            Me.columnNGAY_TAO = New System.Data.DataColumn("NGAY_TAO", GetType(Date), Nothing, System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnNGAY_TAO)
            Me.columnNGUOI_TAO = New System.Data.DataColumn("NGUOI_TAO", GetType(String), Nothing, System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnNGUOI_TAO)
            Me.columnTRANG_THAI = New System.Data.DataColumn("TRANG_THAI", GetType(String), Nothing, System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnTRANG_THAI)
            Me.columnBUILT_IN_YN = New System.Data.DataColumn("BUILT_IN_YN", GetType(String), Nothing, System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnBUILT_IN_YN)
            Me.Constraints.Add(New System.Data.UniqueConstraint("DS_HT_NGUOI_SU_DUNGKey1", New System.Data.DataColumn() {Me.columnID}, true))
            Me.columnID.AllowDBNull = false
            Me.columnID.Unique = true
            Me.columnTEN_TRUY_CAP.AllowDBNull = false
            Me.columnTEN.AllowDBNull = false
            Me.columnMAT_KHAU.AllowDBNull = false
            Me.columnNGAY_TAO.AllowDBNull = false
            Me.columnNGUOI_TAO.AllowDBNull = false
            Me.columnTRANG_THAI.AllowDBNull = false
            Me.columnBUILT_IN_YN.AllowDBNull = false
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function NewHT_NGUOI_SU_DUNGRow() As HT_NGUOI_SU_DUNGRow
            Return CType(Me.NewRow,HT_NGUOI_SU_DUNGRow)
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Function NewRowFromBuilder(ByVal builder As System.Data.DataRowBuilder) As System.Data.DataRow
            Return New HT_NGUOI_SU_DUNGRow(builder)
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Function GetRowType() As System.Type
            Return GetType(HT_NGUOI_SU_DUNGRow)
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowChanged(ByVal e As System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.HT_NGUOI_SU_DUNGRowChangedEvent) Is Nothing) Then
                RaiseEvent HT_NGUOI_SU_DUNGRowChanged(Me, New HT_NGUOI_SU_DUNGRowChangeEvent(CType(e.Row,HT_NGUOI_SU_DUNGRow), e.Action))
            End If
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowChanging(ByVal e As System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.HT_NGUOI_SU_DUNGRowChangingEvent) Is Nothing) Then
                RaiseEvent HT_NGUOI_SU_DUNGRowChanging(Me, New HT_NGUOI_SU_DUNGRowChangeEvent(CType(e.Row,HT_NGUOI_SU_DUNGRow), e.Action))
            End If
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowDeleted(ByVal e As System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.HT_NGUOI_SU_DUNGRowDeletedEvent) Is Nothing) Then
                RaiseEvent HT_NGUOI_SU_DUNGRowDeleted(Me, New HT_NGUOI_SU_DUNGRowChangeEvent(CType(e.Row,HT_NGUOI_SU_DUNGRow), e.Action))
            End If
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowDeleting(ByVal e As System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.HT_NGUOI_SU_DUNGRowDeletingEvent) Is Nothing) Then
                RaiseEvent HT_NGUOI_SU_DUNGRowDeleting(Me, New HT_NGUOI_SU_DUNGRowChangeEvent(CType(e.Row,HT_NGUOI_SU_DUNGRow), e.Action))
            End If
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub RemoveHT_NGUOI_SU_DUNGRow(ByVal row As HT_NGUOI_SU_DUNGRow)
            Me.Rows.Remove(row)
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Shared Function GetTypedTableSchema(ByVal xs As System.Xml.Schema.XmlSchemaSet) As System.Xml.Schema.XmlSchemaComplexType
            Dim type As System.Xml.Schema.XmlSchemaComplexType = New System.Xml.Schema.XmlSchemaComplexType
            Dim sequence As System.Xml.Schema.XmlSchemaSequence = New System.Xml.Schema.XmlSchemaSequence
            Dim ds As DS_HT_NGUOI_SU_DUNG = New DS_HT_NGUOI_SU_DUNG
            xs.Add(ds.GetSchemaSerializable)
            Dim any1 As System.Xml.Schema.XmlSchemaAny = New System.Xml.Schema.XmlSchemaAny
            any1.Namespace = "http://www.w3.org/2001/XMLSchema"
            any1.MinOccurs = New Decimal(0)
            any1.MaxOccurs = Decimal.MaxValue
            any1.ProcessContents = System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any1)
            Dim any2 As System.Xml.Schema.XmlSchemaAny = New System.Xml.Schema.XmlSchemaAny
            any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1"
            any2.MinOccurs = New Decimal(1)
            any2.ProcessContents = System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any2)
            Dim attribute1 As System.Xml.Schema.XmlSchemaAttribute = New System.Xml.Schema.XmlSchemaAttribute
            attribute1.Name = "namespace"
            attribute1.FixedValue = ds.Namespace
            type.Attributes.Add(attribute1)
            Dim attribute2 As System.Xml.Schema.XmlSchemaAttribute = New System.Xml.Schema.XmlSchemaAttribute
            attribute2.Name = "tableTypeName"
            attribute2.FixedValue = "HT_NGUOI_SU_DUNGDataTable"
            type.Attributes.Add(attribute2)
            type.Particle = sequence
            Return type
        End Function
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")>  _
    Partial Public Class HT_NGUOI_SU_DUNGRow
        Inherits System.Data.DataRow
        
        Private tableHT_NGUOI_SU_DUNG As HT_NGUOI_SU_DUNGDataTable
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Friend Sub New(ByVal rb As System.Data.DataRowBuilder)
            MyBase.New(rb)
            Me.tableHT_NGUOI_SU_DUNG = CType(Me.Table,HT_NGUOI_SU_DUNGDataTable)
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property ID() As Decimal
            Get
                Return CType(Me(Me.tableHT_NGUOI_SU_DUNG.IDColumn),Decimal)
            End Get
            Set
                Me(Me.tableHT_NGUOI_SU_DUNG.IDColumn) = value
            End Set
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property TEN_TRUY_CAP() As String
            Get
                Return CType(Me(Me.tableHT_NGUOI_SU_DUNG.TEN_TRUY_CAPColumn),String)
            End Get
            Set
                Me(Me.tableHT_NGUOI_SU_DUNG.TEN_TRUY_CAPColumn) = value
            End Set
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property TEN() As String
            Get
                Return CType(Me(Me.tableHT_NGUOI_SU_DUNG.TENColumn),String)
            End Get
            Set
                Me(Me.tableHT_NGUOI_SU_DUNG.TENColumn) = value
            End Set
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property MAT_KHAU() As String
            Get
                Return CType(Me(Me.tableHT_NGUOI_SU_DUNG.MAT_KHAUColumn),String)
            End Get
            Set
                Me(Me.tableHT_NGUOI_SU_DUNG.MAT_KHAUColumn) = value
            End Set
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property NGAY_TAO() As Date
            Get
                Return CType(Me(Me.tableHT_NGUOI_SU_DUNG.NGAY_TAOColumn),Date)
            End Get
            Set
                Me(Me.tableHT_NGUOI_SU_DUNG.NGAY_TAOColumn) = value
            End Set
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property NGUOI_TAO() As String
            Get
                Return CType(Me(Me.tableHT_NGUOI_SU_DUNG.NGUOI_TAOColumn),String)
            End Get
            Set
                Me(Me.tableHT_NGUOI_SU_DUNG.NGUOI_TAOColumn) = value
            End Set
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property TRANG_THAI() As String
            Get
                Return CType(Me(Me.tableHT_NGUOI_SU_DUNG.TRANG_THAIColumn),String)
            End Get
            Set
                Me(Me.tableHT_NGUOI_SU_DUNG.TRANG_THAIColumn) = value
            End Set
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property BUILT_IN_YN() As String
            Get
                Return CType(Me(Me.tableHT_NGUOI_SU_DUNG.BUILT_IN_YNColumn),String)
            End Get
            Set
                Me(Me.tableHT_NGUOI_SU_DUNG.BUILT_IN_YNColumn) = value
            End Set
        End Property
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")>  _
    Public Class HT_NGUOI_SU_DUNGRowChangeEvent
        Inherits System.EventArgs
        
        Private eventRow As HT_NGUOI_SU_DUNGRow
        
        Private eventAction As System.Data.DataRowAction
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub New(ByVal row As HT_NGUOI_SU_DUNGRow, ByVal action As System.Data.DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Row() As HT_NGUOI_SU_DUNGRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Action() As System.Data.DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
