///************************************************
/// Generated by: MinhNN
/// Date: 19/08/2011 11:38:29
/// Goal: Create User Service Class for DM_CUSTOMER_GROUP
///************************************************
/// <summary>
/// Create User Service Class for DM_CUSTOMER_GROUP
/// </summary>


using SaleDS;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;


namespace SaleUS
{
public class US_DM_CUSTOMER_GROUP : US_Object
{
	private const string c_TableName = "DM_CUSTOMER_GROUP";
#region Public Properties
	public decimal dcID 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID"] = value;
		}
	}

	public bool IsIDNull()	{
		return pm_objDR.IsNull("ID");
	}

	public void SetIDNull() {
		pm_objDR["ID"] = System.Convert.DBNull;
	}

	public string strCUSTOMER_GROUP_NAME 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "CUSTOMER_GROUP_NAME", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["CUSTOMER_GROUP_NAME"] = value;
		}
	}

	public bool IsCUSTOMER_GROUP_NAMENull() 
	{
		return pm_objDR.IsNull("CUSTOMER_GROUP_NAME");
	}

	public void SetCUSTOMER_GROUP_NAMENull() {
		pm_objDR["CUSTOMER_GROUP_NAME"] = System.Convert.DBNull;
	}

#endregion


#region Init Functions
	public US_DM_CUSTOMER_GROUP() 
	{
		pm_objDS = new DS_DM_CUSTOMER_GROUP();
		pm_strTableName = c_TableName;
		pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
	}

	public US_DM_CUSTOMER_GROUP(DataRow i_objDR): this()
	{
		this.DataRow2Me(i_objDR);
	}

	public US_DM_CUSTOMER_GROUP(decimal i_dbID) 
	{
		pm_objDS = new DS_DM_CUSTOMER_GROUP();
		pm_strTableName = c_TableName;
		IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
		v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
		SqlCommand v_cmdSQL;
		v_cmdSQL = v_objMkCmd.getSelectCmd();
		this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
		pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
	}
#endregion


  }
}
