///************************************************
/// Generated by: tund
/// Date: 21/08/2011 04:07:36
/// Goal: Create User Service Class for DM_REPOSITORY
///************************************************
/// <summary>
/// Create User Service Class for DM_REPOSITORY
/// </summary>


using SaleDS;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;


namespace SaleUS
{
public class US_DM_REPOSITORY : US_Object
{
	private const string c_TableName = "DM_REPOSITORY";
#region Public Properties
	public decimal dcID 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID"] = value;
		}
	}

	public bool IsIDNull()	{
		return pm_objDR.IsNull("ID");
	}

	public void SetIDNull() {
		pm_objDR["ID"] = System.Convert.DBNull;
	}

	public string strREPOSITORY_CODE 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "REPOSITORY_CODE", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["REPOSITORY_CODE"] = value;
		}
	}

	public bool IsREPOSITORY_CODENull() 
	{
		return pm_objDR.IsNull("REPOSITORY_CODE");
	}

	public void SetREPOSITORY_CODENull() {
		pm_objDR["REPOSITORY_CODE"] = System.Convert.DBNull;
	}

	public string strREPOSITORY_NAME 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "REPOSITORY_NAME", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["REPOSITORY_NAME"] = value;
		}
	}

	public bool IsREPOSITORY_NAMENull() 
	{
		return pm_objDR.IsNull("REPOSITORY_NAME");
	}

	public void SetREPOSITORY_NAMENull() {
		pm_objDR["REPOSITORY_NAME"] = System.Convert.DBNull;
	}

	public string strADDRESS 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "ADDRESS", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["ADDRESS"] = value;
		}
	}

	public bool IsADDRESSNull() 
	{
		return pm_objDR.IsNull("ADDRESS");
	}

	public void SetADDRESSNull() {
		pm_objDR["ADDRESS"] = System.Convert.DBNull;
	}

	public string strMOBILE 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "MOBILE", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["MOBILE"] = value;
		}
	}

	public bool IsMOBILENull() 
	{
		return pm_objDR.IsNull("MOBILE");
	}

	public void SetMOBILENull() {
		pm_objDR["MOBILE"] = System.Convert.DBNull;
	}

#endregion


#region Init Functions
	public US_DM_REPOSITORY() 
	{
		pm_objDS = new DS_DM_REPOSITORY();
		pm_strTableName = c_TableName;
		pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
	}

	public US_DM_REPOSITORY(DataRow i_objDR): this()
	{
		this.DataRow2Me(i_objDR);
	}

	public US_DM_REPOSITORY(decimal i_dbID) 
	{
		pm_objDS = new DS_DM_REPOSITORY();
		pm_strTableName = c_TableName;
		IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
		v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
		SqlCommand v_cmdSQL;
		v_cmdSQL = v_objMkCmd.getSelectCmd();
		this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
		pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
	}
#endregion


  }
}
