///************************************************
/// Generated by: linhdh
/// Date: 28/08/2011 04:38:25
/// Goal: Create User Service Class for V_GD_PRODUCT_PRICE
///************************************************
/// <summary>
/// Create User Service Class for V_GD_PRODUCT_PRICE
/// </summary>

using System;
using SaleDS;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;


namespace SaleUS
{
public class US_V_GD_PRODUCT_PRICE : US_Object
{
	private const string c_TableName = "V_GD_PRODUCT_PRICE";
#region Public Properties
	public decimal dcID 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID"] = value;
		}
	}

	public bool IsIDNull()	{
		return pm_objDR.IsNull("ID");
	}

	public void SetIDNull() {
		pm_objDR["ID"] = System.Convert.DBNull;
	}

	public decimal dcPRODUCT_ID 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "PRODUCT_ID", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["PRODUCT_ID"] = value;
		}
	}

	public bool IsPRODUCT_IDNull()	{
		return pm_objDR.IsNull("PRODUCT_ID");
	}

	public void SetPRODUCT_IDNull() {
		pm_objDR["PRODUCT_ID"] = System.Convert.DBNull;
	}

	public string strPRODUCT_NAME 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "PRODUCT_NAME", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["PRODUCT_NAME"] = value;
		}
	}

	public bool IsPRODUCT_NAMENull() 
	{
		return pm_objDR.IsNull("PRODUCT_NAME");
	}

	public void SetPRODUCT_NAMENull() {
		pm_objDR["PRODUCT_NAME"] = System.Convert.DBNull;
	}

	public DateTime datAPPLY_DATE
	{
		get   
		{
			return CNull.RowNVLDate(pm_objDR, "APPLY_DATE", IPConstants.c_DefaultDate);
		}
		set   
		{
			pm_objDR["APPLY_DATE"] = value;
		}
	}

	public bool IsAPPLY_DATENull()
	{
		return pm_objDR.IsNull("APPLY_DATE");
	}

	public void SetAPPLY_DATENull()
	{
		pm_objDR["APPLY_DATE"] = System.Convert.DBNull;
	}

	public decimal dcPRICE 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "PRICE", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["PRICE"] = value;
		}
	}

	public bool IsPRICENull()	{
		return pm_objDR.IsNull("PRICE");
	}

	public void SetPRICENull() {
		pm_objDR["PRICE"] = System.Convert.DBNull;
	}

	public decimal dcUNIT_ID 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "UNIT_ID", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["UNIT_ID"] = value;
		}
	}

	public bool IsUNIT_IDNull()	{
		return pm_objDR.IsNull("UNIT_ID");
	}

	public void SetUNIT_IDNull() {
		pm_objDR["UNIT_ID"] = System.Convert.DBNull;
	}

	public string strUNIT_CODE 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "UNIT_CODE", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["UNIT_CODE"] = value;
		}
	}

	public bool IsUNIT_CODENull() 
	{
		return pm_objDR.IsNull("UNIT_CODE");
	}

	public void SetUNIT_CODENull() {
		pm_objDR["UNIT_CODE"] = System.Convert.DBNull;
	}

	public string strDESCRIPTION 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "DESCRIPTION", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["DESCRIPTION"] = value;
		}
	}

	public bool IsDESCRIPTIONNull() 
	{
		return pm_objDR.IsNull("DESCRIPTION");
	}

	public void SetDESCRIPTIONNull() {
		pm_objDR["DESCRIPTION"] = System.Convert.DBNull;
	}

#endregion


#region Init Functions
	public US_V_GD_PRODUCT_PRICE() 
	{
		pm_objDS = new DS_V_GD_PRODUCT_PRICE();
		pm_strTableName = c_TableName;
		pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
	}

	public US_V_GD_PRODUCT_PRICE(DataRow i_objDR): this()
	{
		this.DataRow2Me(i_objDR);
	}

	public US_V_GD_PRODUCT_PRICE(decimal i_dbID) 
	{
		pm_objDS = new DS_V_GD_PRODUCT_PRICE();
		pm_strTableName = c_TableName;
		IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
		v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
		SqlCommand v_cmdSQL;
		v_cmdSQL = v_objMkCmd.getSelectCmd();
		this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
		pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
	}
#endregion

    #region Additional Function
    public void Insert_to_product_price(decimal ip_dc_product_id,
                                        DateTime ip_dat_applied_date, decimal ip_dc_price, decimal ip_dc_unit_id)
    {
        CStoredProc v_store = new CStoredProc("pr_V_GD_PRODUCT_PRICE_Insert");
        v_store.addDecimalInputParam("@PRODUCT_ID",ip_dc_product_id);
        v_store.addDatetimeInputParam("@APPLY_DATE", ip_dat_applied_date);
        v_store.addDecimalInputParam("@PRICE", ip_dc_price);
        v_store.addDecimalInputParam("@UNIT_ID", ip_dc_unit_id);
        v_store.ExecuteCommand(this);
    }
    #endregion
}
}
